### ISSUE TITLE
Layout pages with COSArray currently not supported. 

### ISSUE THREAD

**Issue by RCatersels** [mendix/CommunityCommons#14]
When using the overlay function we get the error below. From stackoverflow this seems to be a known issue and has the overlay function been simplyfied. See stackoverflow here:
http://stackoverflow.com/questions/31178087/pdfbox-1-8-9-overlay-two-pdf-documents-layout-pages-with-cosarray-currently-not

Sollution would be to upgrade to at least pdfbox-1.8.10.jar. 

Regards,

Ronald

com.mendix.modules.microflowengine.MicroflowException: com.mendix.core.CoreRuntimeException: java.lang.UnsupportedOperationException: Layout pages with COSArray currently not supported. 
at MutatiesKoppeling.Mutatie_Print_Archief_Uitdraaidatum (JavaAction : 'Call 'OverlayPdfDocument'') 
at MutatiesKoppeling.Mutatie_Print_Archief_Downloaden (SubMicroflow : 'Call 'Mutatie_Print_Archief_Uitdraaidatum'') 

Advanced stacktrace: 
at com.mendix.modules.microflowengine.microflow.MicroflowObject.processException(MicroflowObject.java:190) 
Caused by: com.mendix.core.CoreException: com.mendix.core.CoreRuntimeException: java.lang.UnsupportedOperationException: Layout pages with COSArray currently not supported. 
at com.mendix.core.Core.execute(Core.java:232) 
Caused by: com.mendix.core.CoreRuntimeException: java.lang.UnsupportedOperationException: Layout pages with COSArray currently not supported. 
at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:209) 
Caused by: java.lang.UnsupportedOperationException: Layout pages with COSArray currently not supported. 
at org.apache.pdfbox.Overlay.collectLayoutPages(Overlay.java:269) 
at org.apache.pdfbox.Overlay.overlay(Overlay.java:224) 
at communitycommons.Misc.overlayPdf(Misc.java:619) 
at communitycommons.actions.OverlayPdfDocument.executeAction(OverlayPdfDocument.java:41) 
at communitycommons.actions.OverlayPdfDocument.executeAction(OverlayPdfDocument.java:19) 
at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:57) 
at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:478) 
at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:463) 
at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:198) 
at com.mendix.core.Core.execute(Core.java:226)

**Comment by RCatersels** [comment]
PDFBox is currently on version 2.0.3 but in this module still on 1.8.5. Will it be updated?

**Comment by RoelandSalij** [comment]
Updated in v6.0
